name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - master  # Trigger on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.DIGITALOCEAN_USER }}@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
            cd /root/oneshop-api  # Navigate to FastAPI project directory
            git pull origin master  # Pull latest changes
            docker compose down  # Stop running containers
            docker compose up -d --build  # Rebuild and restart FastAPI
          EOF
